// --== CS400 Project Two File Header ==--
// Name: Yun Li
// CSL Username: <yunl>
// Email: <li2459@wisc.edu>
// Lecture #: <001 @11:00am>
// Notes to Grader: <>

import java.util.List;
import java.io.FileNotFoundException;
import java.util.ArrayList;

/**
 * Instances of classes that implement this interface can be used to load a
 * list of airplanes objects from a specified XML source file.
 */
public interface IAirplaneLoader {

    /**
     * This method loads the list of elements within the XML file generated by
     * IGenerateData class.
     * 
     * @param filepath is relative to executable's working directory
     * @return a list of airplane objects that were read from specified file
     */
    ArrayList<IAirplane> loadAirport(String filepath) throws FileNotFoundException;

}
